### ISSUE TITLE
Create basic structures and add necessary files for the services

### ISSUE THREAD

**Issue by Xaptured** [Xaptured/TheJackFolioParentRepository#1]
This is an epic which will be having all the subtasks. These subtasks may be related to basic structures of the services or necessary files to implement business logics. 

## Subtasks can be from any of the services which are mentioned below:

- microservice-thejackfolio_db
- microservice-client
- microservice-profession
- microservice-youtube
- microservice-instagram
- microservice-instagram-oauth-client

## Subtasks

- [ ] https://github.com/Xaptured/microservice-client/issues/3
- [ ] https://github.com/Xaptured/microservice-instagram/issues/1
- [ ] https://github.com/Xaptured/microservice-youtube/issues/1
- [ ] https://github.com/Xaptured/microservice-profession/issues/1
- [ ] https://github.com/Xaptured/microservice-thejackfolio_db/issues/1
- [ ] https://github.com/Xaptured/microservice-instagram-oauth-client/issues/3
- [ ] https://github.com/Xaptured/microservice-thejackfolio_db/issues/3
- [ ] https://github.com/Xaptured/microservice-client/issues/5
- [ ] https://github.com/Xaptured/microservice-profession/issues/3
- [ ] https://github.com/Xaptured/microservice-instagram/issues/3
- [ ] https://github.com/Xaptured/microservice-youtube/issues/3
- [ ] https://github.com/Xaptured/microservice-thejackfolio_db/issues/4
- [ ] https://github.com/Xaptured/microservice-thejackfolio_db/issues/7
- [ ] https://github.com/Xaptured/microservice-thejackfolio_db/issues/16
- [ ] https://github.com/Xaptured/microservice-thejackfolio_db/issues/22
- [ ] https://github.com/Xaptured/microservice-thejackfolio_db/issues/24
- [ ] https://github.com/Xaptured/microservice-instagram-oauth-client/issues/7
- [ ] https://github.com/Xaptured/microservice-instagram/issues/13
- [ ] https://github.com/Xaptured/microservice-instagram-oauth-client/issues/10
- [ ] https://github.com/Xaptured/microservice-instagram/issues/15
- [ ] https://github.com/Xaptured/microservice-instagram-oauth-client/issues/12
- [ ] https://github.com/Xaptured/microservice-instagram/issues/17
- [ ] https://github.com/Xaptured/microservice-youtube/issues/11
- [ ] https://github.com/Xaptured/microservice-client/issues/18
- [ ] https://github.com/Xaptured/microservice-profession/issues/13
- [ ] https://github.com/Xaptured/microservice-thejackfolio_db/issues/27
