### ISSUE TITLE
Fix BUGS

### ISSUE THREAD

**Issue by Xaptured** [Xaptured/TheJackFolioParentRepository#2]
This is an epic which will be having all the subtasks related to bugs from all the services.

## Subtasks can be from any of the services which are mentioned below:

- microservice-thejackfolio_db
- microservice-client
- microservice-profession
- microservice-youtube
- microservice-instagram
- microservice-instagram-oauth-client

## Subtasks

- [ ] https://github.com/Xaptured/microservice-client/issues/13
- [ ] https://github.com/Xaptured/microservice-profession/issues/5
- [ ] https://github.com/Xaptured/microservice-client/issues/15
- [ ] https://github.com/Xaptured/microservice-thejackfolio_db/issues/19
- [ ] https://github.com/Xaptured/microservice-instagram/issues/10
