### ISSUE TITLE
Create necessary documents

### ISSUE THREAD

**Issue by Xaptured** [Xaptured/TheJackFolioParentRepository#3]
This is an epic which will be having all the subtasks. These subtasks may be related to investigation documents, updating README files and API requests which can be used to do Integration Testing.

## Subtasks can be from any of the services which are mentioned below:

- microservice-thejackfolio_db
- microservice-client
- microservice-profession
- microservice-youtube
- microservice-instagram
- microservice-instagram-oauth-client
- microservice-registry
- microservice-api-gateway
- thejackfolio_dashboard

## Subtasks

- [x] https://github.com/Xaptured/microservice-thejackfolio_db/issues/11
- [x] https://github.com/Xaptured/microservice-client/issues/14
- [x] https://github.com/Xaptured/microservice-profession/issues/8
- [x] https://github.com/Xaptured/microservice-youtube/issues/10
- [x] https://github.com/Xaptured/microservice-instagram/issues/9
- [x] https://github.com/Xaptured/microservice-instagram-oauth-client/issues/6
- [x] https://github.com/Xaptured/microservice-youtube/issues/4
- [x] https://github.com/Xaptured/microservice-instagram/issues/4
- [x] https://github.com/Xaptured/microservice-thejackfolio_db/issues/25
- [x] https://github.com/Xaptured/microservice-instagram/issues/19
- [x] https://github.com/Xaptured/microservice-client/issues/20
- [x] https://github.com/Xaptured/microservice-profession/issues/15
- [x] https://github.com/Xaptured/microservice-instagram-oauth-client/issues/14
- [x] https://github.com/Xaptured/microservice-youtube/issues/13
- [x] https://github.com/Xaptured/microservice-registry/issues/5
- [x] https://github.com/Xaptured/microservice-api-gateway/issues/3
- [x] https://github.com/Xaptured/thejackfolio_dashboard/issues/3
- [x] https://github.com/Xaptured/thejackfolio_dashboard/issues/5
- [x] https://github.com/Xaptured/microservice-thejackfolio_db/issues/56
- [x] https://github.com/Xaptured/microservice-thejackfolio_db/issues/57
- [x] https://github.com/Xaptured/microservice-thejackfolio_db/issues/58
