### ISSUE TITLE
Create necessary test cases for UT and do Integrated testing

### ISSUE THREAD

**Issue by Xaptured** [Xaptured/TheJackFolioParentRepository#4]
This is an epic which will be having all the subtasks. These subtasks may be related to unit test cases or performing Integrated Tests.

## Subtasks can be from any of the services which are mentioned below:

- microservice-thejackfolio_db
- microservice-client
- microservice-profession
- microservice-youtube
- microservice-instagram
- microservice-instagram-oauth-client

## Subtasks

- [ ] https://github.com/Xaptured/microservice-thejackfolio_db/issues/6
- [ ] https://github.com/Xaptured/microservice-thejackfolio_db/issues/13
- [ ] https://github.com/Xaptured/microservice-client/issues/7
- [ ] https://github.com/Xaptured/microservice-client/issues/8
- [ ] https://github.com/Xaptured/microservice-profession/issues/10
- [ ] https://github.com/Xaptured/microservice-profession/issues/11
- [ ] https://github.com/Xaptured/microservice-youtube/issues/8
- [ ] https://github.com/Xaptured/microservice-youtube/issues/9
- [ ] https://github.com/Xaptured/microservice-instagram/issues/6
- [ ] https://github.com/Xaptured/microservice-instagram/issues/7
- [ ] https://github.com/Xaptured/microservice-instagram-oauth-client/issues/8
- [ ] https://github.com/Xaptured/microservice-instagram-oauth-client/issues/9
