### ISSUE TITLE
Configurations related to DataBase or Repositories

### ISSUE THREAD

**Issue by Xaptured** [Xaptured/TheJackFolioParentRepository#5]
This is an epic which will be having all the subtasks. These subtasks may be related to DB configurations or Reository Configurations

## Subtasks can be from any of the services which are mentioned below:

- microservice-thejackfolio_db
- microservice-client
- microservice-profession
- microservice-youtube
- microservice-instagram
- microservice-instagram-oauth-client

## Subtasks

- [ ] https://github.com/Xaptured/microservice-thejackfolio_db/issues/5
- [ ] https://github.com/Xaptured/microservice-thejackfolio_db/issues/14
- [ ] https://github.com/Xaptured/microservice-client/issues/12
- [ ] https://github.com/Xaptured/microservice-profession/issues/4
- [ ] https://github.com/Xaptured/microservice-youtube/issues/5
- [ ] https://github.com/Xaptured/microservice-instagram/issues/5
- [ ] https://github.com/Xaptured/microservice-instagram-oauth-client/issues/1
