### ISSUE TITLE
Create basic structures and components for the dashboard

### ISSUE THREAD

**Issue by Xaptured** [Xaptured/TheJackFolioParentRepository#6]
## Subtasks

- [ ] https://github.com/Xaptured/thejackfolio_dashboard/issues/1
- [ ] https://github.com/Xaptured/thejackfolio_dashboard/issues/2
- [ ] https://github.com/Xaptured/thejackfolio_dashboard/issues/3
